#include "packaging/PackagingResultWriter.h"
#include <filesystem>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;
using json = nlohmann::ordered_json;

static void ensure_dir(const fs::path& p) {
    if (!fs::exists(p)) fs::create_directories(p);
}

static void write_json(const fs::path& p, const json& j) {
    std::ofstream f(p.string(), std::ios::binary);
    f << j.dump(2);
}

static void write_text(const fs::path& p, const std::string& s) {
    std::ofstream f(p.string(), std::ios::binary);
    f << s;
}

static std::string basename_noext(const std::string& path) {
    try {
        return fs::path(path).stem().string();
    }
    catch (...) {
        return "model";
    }
}

void PackagingResultWriter::writeAll(const PackagingTaskRequestLite& req,
    const std::string& outPackagingResultDir,
    const json& resultMetadata,
    const json& detectedModelMeta,
    const json& mappingTable,
    const json& unmatchedItems,
    const json& warnings,
    const json& compatibilityChecks,
    const json& modelParserMeta,
    const std::string& requestPath,
    const std::string& modelPath,
    const std::string& frameworkParseLogText,
    const json& frameworkIoDump) {

    fs::path root(outPackagingResultDir);
    ensure_dir(root);
    ensure_dir(root / "generated-src");
    ensure_dir(root / "generated-src" / "include");
    ensure_dir(root / "generated-src" / "src");
    ensure_dir(root / "generated-docs");
    ensure_dir(root / "raw-extract");

    // Required JSON outputs
    write_json(root / "Result_Metadata.json", resultMetadata);
    write_json(root / "Detected_Model_Meta.json", detectedModelMeta);
    write_json(root / "Mapping_Table.json", mappingTable);
    write_json(root / "Unmatched_Items.json", unmatchedItems);
    write_json(root / "Warnings.json", warnings);
    write_json(root / "Compatibility_Checks.json", compatibilityChecks);

    // raw-extract: keep original extraction artifacts (best-effort, not a stable API)
    // 1) ModelParser metajson content (fixed name)
    if (!modelParserMeta.is_null() && !modelParserMeta.empty()) {
        write_json(root / "raw-extract" / "ModelParser_Meta.json", modelParserMeta);
    }

    // 2) Copy request/model path info (useful for traceability)
    json trace;
    trace["requestPath"] = requestPath;
    trace["modelPath"] = modelPath;
    trace["taskId"] = req.taskId;
    trace["blockKey"] = req.blockKey;
    trace["blockName"] = req.blockName;
    trace["wrapperClassName"] = req.generationOptions.nameSpace + "::" + req.generationOptions.className;
    write_json(root / "raw-extract" / "Trace.json", trace);

    // 3) framework_parse_log.txt
    if (!frameworkParseLogText.empty()) {
        write_text(root / "raw-extract" / "framework_parse_log.txt", frameworkParseLogText);
    }

    // 4) TF/PT framework io dump (tf_io_dump.json or torch_io_dump.json)
    if (!frameworkIoDump.is_null() && !frameworkIoDump.empty()) {
        const std::string& implType = req.implementationType;
        std::string dumpName;
        if (implType == "TensorFlow") {
            dumpName = "tf_io_dump.json";
        } else if (implType == "PyTorch") {
            dumpName = "torch_io_dump.json";
        } else {
            dumpName = "framework_io_dump.json";
        }
        write_json(root / "raw-extract" / dumpName, frameworkIoDump);
    }

    // docs: README
    std::ostringstream md;
    md
        << "# Packaging Result\n\n"
        << "This directory is generated by `AiModelPackagingCLI`.\n\n"
        << "## Inputs\n"
        << "- Request: `" << requestPath << "`\n"
        << "- Model: `" << modelPath << "`\n\n"
        << "## Directory structure\n"
        << "```\n"
        << ".\n"
        << "+-- Result_Metadata.json\n"
        << "+-- Detected_Model_Meta.json\n"
        << "+-- Mapping_Table.json\n"
        << "+-- Unmatched_Items.json\n"
        << "+-- Warnings.json\n"
        << "+-- Compatibility_Checks.json\n"
        << "+-- raw-extract/\n"
        << "|   +-- ModelParser_Meta.json    (ONNX only)\n"
        << "|   +-- tf_io_dump.json          (TensorFlow only)\n"
        << "|   +-- torch_io_dump.json       (PyTorch only)\n"
        << "|   +-- Trace.json\n"
        << "|   +-- framework_parse_log.txt\n"
        << "+-- generated-src/\n"
        << "|   +-- include/\n"
        << "|   +-- src/\n"
        << "+-- generated-docs/\n"
        << "    +-- README.md\n"
        << "```\n\n"
        << "## Notes\n"
        << "- `raw-extract/ModelParser_Meta.json` is the original output produced by `ModelParser` (ONNX).\n"
        << "- `raw-extract/tf_io_dump.json` is the raw output of the TensorFlow meta-extraction script.\n"
        << "- `raw-extract/torch_io_dump.json` is the raw output of the PyTorch meta-extraction script.\n"
        << "- `raw-extract/framework_parse_log.txt` records the framework parse result for traceability.\n"
        << "- `generated-src/` contains the generated wrapper source code.\n"
        << "- For TF/PT: inference is not implemented in the generated runtime stub; "
           "use the generated header/source as a starting point.\n";

    write_text(root / "generated-docs" / "README.md", md.str());
}